#!/usr/bin/env ruby-1.9.2-p180-patched@pivotal

require "rubygems"
require "curb"
require "nokogiri"

def self.extract_msgs(ids, types, names)
  (0...ids.size).map do |i|
    "[#{ids[i].text}] ##{types[i].text.upcase} #{names[i].text}"
  end
end

request = Curl::Easy.new("http://www.pivotaltracker.com/services/v3/projects/#{ENV['PROJECT_ID']}/stories?filter=state%3Astarted%20owner%3A#{ENV['OWNER_ID']}")
request.headers["X-TrackerToken"] = ENV['PT_TOKEN']
request.perform

xml = Nokogiri::XML(request.body_str)

msgs = extract_msgs(
         xml.xpath('//story/id'),
         xml.xpath('//story/story_type'),
         xml.xpath('//story/name')
       )

unless msgs.nil?
  commit_msg = msgs.join("\n")

  path       = ARGV.first
  lines      = IO.readlines(path)
  lines[0]   = commit_msg

  File.open(path, 'w') { |file| file.puts lines }
end